### ISSUE TITLE
Route Registrar leaks password info when creating nats connection

### ISSUE THREAD

**Issue by youreddy** [cloudfoundry-incubator/route-registrar#16]
Hey Routing!

The registrar logs the config directly, which is configured with passwords. These passwords aren't redacted.

https://github.com/cloudfoundry-incubator/route-registrar/blob/master/registrar/registrar.go#L51

@youreddy && @chendrix
CF Core Services

**Comment by youreddy** [comment]
Thanks for that commit!

**Comment by youreddy** [comment]
JK, still leaking

https://github.com/cloudfoundry-incubator/route-registrar/blob/master/messagebus/messagebus.go#L48

**Comment by shashwathi** [comment]
@youreddy : We have removed logging sensitive information in [this](https://github.com/cloudfoundry-incubator/route-registrar/commit/0dc9d2b21e8c4e16729ce219183d8a4209b25540) commit. Closing this issue for now.

Regards
Shash
