### ISSUE TITLE
Missing godep for github.com/pivotal-cf-experimental/service-config

### ISSUE THREAD

**Issue by avade** [cloudfoundry-incubator/route-registrar#2]
Currently we (@markgalpin) think there is a missing godep for github.com/pivotal-cf-experimental/service-config.

If I get a chance I will config & send a pull request.

**Comment by menicosia** [comment]
Hi @avade,

OK, any hints in the meanwhile? I think this is something that's part of our CI (since we use it to configure a variety of our sub-modules), so unless I ask the team to just start hunting for obvious errors...?

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by robdimsdale** [comment]
There is very likely missing Godeps in this repo, as this repo is often used in conjunction with other dependency management techniques (such as a bosh-release directory doubling up as the GOPATH).

It should be fairly easy to fix this issue, but perhaps a more interesting question is, is this something the team wishes to support? Do the maintainers of this project have any use for Godeps at all?

**Comment by markgalpin** [comment]
This issue appears to have been resolved with the merge of siddhuwarrier-master

**Comment by menicosia** [comment]
OK, thanks for following up, @markgalpin!

--
Marco Nicosia
Product Manager
Pivotal Software, Inc.
