### ISSUE TITLE
How does one install and use this?

### ISSUE THREAD

**Issue by shalako** [cloudfoundry-incubator/route-registrar#5]
I'd like to see instructions, assuming no knowledge of go, for downloading and running this tool to register a route with gorouter via NATS.

I've tried cloning the repo. There's no bin directory, and no instructions for building.

I've tried `go get` as this is rumored to be something you do with go projects. The error is not helpful. 
```
$ go get github.com/cloudfoundry-incubator/route-registrar
# github.com/cloudfoundry-incubator/route-registrar/registrar
../go/src/github.com/cloudfoundry-incubator/route-registrar/registrar/registrar.go:43: cannot use messageBus (type yagnats.NATSClient) as type yagnats.NATSConn in argument to gibson.NewCFRouterClient:
	yagnats.NATSClient does not implement yagnats.NATSConn (missing AddClosedCB method)
```

**Comment by shashwathi** [comment]
Hi @shalako 
We have edited README to add more instructions on how to install and use route-registrar.  Please let us know if you have further questions on how to use this module.

**Comment by shalako** [comment]
Thank you!
